services:
 - type: web
   name: openclass-app
   env: python
   buildCommand: "./build.sh"
   startCommand: "gunicorn openclass.wsgi:application"
   plan: free
   autoDeploy: true
   envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: openclass.settings
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: SECRET_KEY
        value: django-insecure-8&#_v7a(vs7*ht0(30a-es^sg1ufes+b3##&(-frbtt5&eih)b
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
            name: openclass-db
            property: connectionString
    databases:
      - openclass-db
            
databases:
    - name: openclass-db
      databaseName: openclass-db
      user: openclass_db_user
     